default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: your_app_name_development
  username: your_postgres_username
  password: your_postgres_password
  host: localhost

test:
  <<: *default
  database: your_app_name_test
  username: your_postgres_username
  password: your_postgres_password
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
